version: 2.0

jobs:
  test:
    docker:
      - image: circleci/node:8-stretch
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

workflows:
  version: 2
  test:
    jobs:
      - test
